### ISSUE TITLE
Updating yarn requires unpinning node

### ISSUE THREAD

**Issue by urkopineda** [nijicha/install_nodejs_and_yarn_homebrew#1]
Thanks for the install instructions! I have a problem upgrading `yarn` after linking and pinning `node` in Homebrew. 

```
➜ brew upgrade
Error: Not upgrading 1 pinned package:
node 12.12.0
==> Upgrading 1 outdated package:
yarn 1.19.0 -> 1.19.1
Error: You must `brew unpin node` as installing yarn requires the latest version of pinned dependencies

~ took 4s 
```

How can be Homebrew forced to update `yarn` without touching `node`? Thanks again!

**Comment by twentyfiffourteen** [comment]
@urkopineda 

Unfortunately.

Currently, Homebrew doesn't provide upgrading of the packages which dependencies pinned to Homebrew.

I will add instructions "How to upgrade `yarn` in Homebrew" later.

😁

**Comment by nijicha** [comment]
@urkopineda

Unfortunately.

Currently, Homebrew doesn't provide upgrading of the packages which dependencies pinned to Homebrew.

I will add instructions "How to upgrade yarn in Homebrew" later.

😁

**Comment by urkopineda** [comment]
Hi @nijicha, thanks for your response! OK, feel free to close the issue whenever you want.

**Comment by nijicha** [comment]
@urkopineda Okay.

**Comment by nijicha** [comment]
@urkopineda 

Part C updated !
https://github.com/nijicha/install_nodejs_and_yarn_homebrew#part-c-upgrading-to-change-nodejs-version-and-re-configure-homebrew

Say yay 🥳
