### ISSUE TITLE
Miultiple yarn / node versions?

### ISSUE THREAD

**Issue by corroded** [nijicha/install_nodejs_and_yarn_homebrew#2]
Does this also work for multiple yarn / node versions? It all seems like it only works for one installation but with nvm. Is this possible to do with say a project using node 10 and yarn 12 and another using node 1.17 and yarn 1.19?

**Comment by nijicha** [comment]
Hi @corroded,

Unfortunately, From this guide.

> Just `yarn` from [Homebrew](https://brew.sh) and `node` from NVM which installed via Homebrew

This `yarn` can be upgrade/downgrade via Homebrew only.

**If you want to upgrade `yarn` from 1.19 to 1.20 and you had pinned yarn to prevent upgrading version (`brew pin yarn`). You need to follow this steps below.**

You need to
1. Unlink `/usr/local/Cellar/node` in NVM from Homebrew folder
2. Unpin `yarn`. To upgrade yarn version.
3. After upgrading `yarn`. You must remove `node` from Homebrew as yarn dependencies.

After re-structure of development library
4. Do Part B. step 5 to 10 again.

Thanks and feel free to close this issue.

**Comment by corroded** [comment]
Thanks for this! Will keep this in mind! Cheers!
