### ISSUE TITLE
Error: No such keg: /opt/homebrew/Cellar/node

### ISSUE THREAD

**Issue by arnaudambro** [nijicha/install_nodejs_and_yarn_homebrew#7]
Hi there

Thanks for this great readme !

I can't go further the step `brew link --overwrite node` though, because this error comes up:

`Error: No such keg: /opt/homebrew/Cellar/node`

what am I missing ?

**Comment by nijicha** [comment]
Hi, @arnaudambro Sorry for the late reply 🥲

It is Apple Silicon binary configure. I guess you need to config your `zsh` to solve the `homebrew` path

Let me show my setup on my Apple silicon machine
1. I have two terminal applications **Terminal** (by default) and **iTerm2**
2. I had installed Rosetta2. And turn rosetta on **Terminal**
    ![Screen Shot 2565-04-21 at 21 26 49](https://user-images.githubusercontent.com/12441214/164480084-905e276d-b549-47c9-8884-1ca63bef9670.png)
3. I installed Homebrew two times by official command https://brew.sh. Once finished I have two homebrew PATH on my machine. The purpose is separate native apple silicon package and legacy intel package base
![Screen Shot 2565-04-21 at 21 30 02](https://user-images.githubusercontent.com/12441214/164480764-5aef98f8-4bc7-4a77-8afa-c1e2b1ecea0e.png)

BTW. I updated the guideline change the version manager also (from nvm to asdf)
Thank you!

**Comment by nijicha** [comment]
@arnaudambro And this is my `.zshrc` configured

```bash
# My .zprofile

# Apple M1
if [ "$(uname -m)" = "arm64" ]; then
  # Use arm64 brew, with fallback to x86 brew
  if [ -f /opt/homebrew/bin/brew ]; then
    export PATH="/usr/local/bin${PATH+:$PATH}";
    eval $(/opt/homebrew/bin/brew shellenv)
  fi
else
  # Use x86 brew, with fallback to arm64 brew
  if [ -f /usr/local/bin/brew ]; then
    export PATH="/opt/homebrew/bin${PATH+:$PATH}";
    eval $(/usr/local/bin/brew shellenv)
  fi
fi
```
